[pytest]
markers =
    muhindhar: Tests developed by muhindhar
    vigneshwaran: Tests developed by vigneshwaran
    jerishwin: Tests developed by jerishwin
    mythily: Tests developed by mythily
    malavicka: Tests developed by malavicka
    flaky: Flaky tests
    dependency: Dependency tests
